# -*- coding: utf-8 -*-
"""final Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12uYxxj35vCvLbhq8l-05Ae1fmLoiiluy
"""

import streamlit as st
import sqlite3
from datetime import date, time
import os

# ============================================================
# PAGE CONFIGURATION
# ============================================================

st.set_page_config(
    page_title="Smart Meeting Room Allocation",
    page_icon="🏢",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ============================================================
# DATABASE
# ============================================================

DB_NAME = "meeting_rooms.db"


def get_connection():
    return sqlite3.connect(
        DB_NAME,
        check_same_thread=False
    )


conn = get_connection()
cursor = conn.cursor()

# ============================================================
# CREATE TABLES
# ============================================================

cursor.execute("""
CREATE TABLE IF NOT EXISTS rooms (
    room_id INTEGER PRIMARY KEY AUTOINCREMENT,
    room_name TEXT UNIQUE NOT NULL,
    capacity INTEGER NOT NULL,
    facilities TEXT NOT NULL
)
""")

cursor.execute("""
CREATE TABLE IF NOT EXISTS bookings (
    booking_id INTEGER PRIMARY KEY AUTOINCREMENT,
    meeting_name TEXT NOT NULL,
    organizer TEXT NOT NULL,
    participants INTEGER NOT NULL,
    room_id INTEGER NOT NULL,
    booking_date TEXT NOT NULL,
    start_time TEXT NOT NULL,
    end_time TEXT NOT NULL,
    FOREIGN KEY(room_id) REFERENCES rooms(room_id)
)
""")

conn.commit()

# ============================================================
# DEFAULT ROOMS
# ============================================================

default_rooms = [
    ("Room A", 4, "None"),
    ("Room B", 8, "Projector"),
    ("Room C", 12, "Projector, Whiteboard"),
    ("Room D", 20, "Projector, Whiteboard")
]

for room in default_rooms:

    cursor.execute(
        "SELECT room_id FROM rooms WHERE room_name = ?",
        (room[0],)
    )

    if cursor.fetchone() is None:

        cursor.execute("""
        INSERT INTO rooms
        (room_name, capacity, facilities)
        VALUES (?, ?, ?)
        """, room)

conn.commit()

# ============================================================
# CSS
# IMPORTANT:
# There is NO HTML used for the actual room/booking content.
# ============================================================

st.markdown(
    """
    <style>

    /* Main background */

    .stApp {
        background-color: #f5f7fb;
    }

    /* Sidebar */

    section[data-testid="stSidebar"] {
        background-color: #172554;
    }

    section[data-testid="stSidebar"] h1,
    section[data-testid="stSidebar"] h2,
    section[data-testid="stSidebar"] h3,
    section[data-testid="stSidebar"] p,
    section[data-testid="stSidebar"] label,
    section[data-testid="stSidebar"] span {
        color: white !important;
    }

    /* Main title */

    .main-title {
        font-size: 42px;
        font-weight: 800;
        color: #172554;
        margin-bottom: 5px;
    }

    .subtitle {
        font-size: 17px;
        color: #64748b;
        margin-bottom: 25px;
    }

    /* Section heading */

    .section-heading {
        font-size: 27px;
        font-weight: 750;
        color: #172554;
        margin-top: 20px;
        margin-bottom: 15px;
    }

    /* Streamlit metric cards */

    [data-testid="stMetric"] {
        background-color: white;
        border: 1px solid #e2e8f0;
        border-radius: 15px;
        padding: 18px;
        box-shadow: 0px 4px 12px rgba(15, 23, 42, 0.06);
    }

    [data-testid="stMetricLabel"] {
        color: #64748b !important;
    }

    [data-testid="stMetricValue"] {
        color: #172554 !important;
        font-weight: 800;
    }

    /* Buttons */

    .stButton > button {
        border-radius: 10px;
        font-weight: 600;
    }

    /* Input labels */

    label {
        font-weight: 600 !important;
    }

    </style>
    """,
    unsafe_allow_html=True
)

# ============================================================
# FUNCTIONS
# ============================================================


def get_rooms():

    cursor.execute("""
    SELECT room_id, room_name, capacity, facilities
    FROM rooms
    ORDER BY capacity
    """)

    return cursor.fetchall()


def is_room_available(
    room_id,
    selected_date,
    start_time,
    end_time
):

    cursor.execute("""
    SELECT booking_id
    FROM bookings
    WHERE room_id = ?
    AND booking_date = ?
    AND start_time < ?
    AND end_time > ?
    """, (
        room_id,
        selected_date,
        end_time,
        start_time
    ))

    return cursor.fetchone() is None


def has_required_facilities(
    room_facilities,
    required_facilities
):

    if not required_facilities:
        return True

    if room_facilities == "None":
        return False

    room_facilities = room_facilities.lower()

    for facility in required_facilities:

        if facility.lower() not in room_facilities:
            return False

    return True


def find_best_room(
    participants,
    required_facilities,
    selected_date,
    start_time,
    end_time
):

    rooms = get_rooms()

    suitable_rooms = []

    for room in rooms:

        room_id = room[0]
        capacity = room[2]
        facilities = room[3]

        # Capacity check
        if capacity < participants:
            continue

        # Facility check
        if not has_required_facilities(
            facilities,
            required_facilities
        ):
            continue

        # Time conflict check
        if not is_room_available(
            room_id,
            selected_date,
            start_time,
            end_time
        ):
            continue

        suitable_rooms.append(room)

    if suitable_rooms:
        return suitable_rooms[0]

    return None


def get_bookings(selected_date):

    cursor.execute("""
    SELECT
        bookings.booking_id,
        bookings.meeting_name,
        bookings.organizer,
        bookings.participants,
        rooms.room_name,
        bookings.start_time,
        bookings.end_time
    FROM bookings
    JOIN rooms
    ON bookings.room_id = rooms.room_id
    WHERE bookings.booking_date = ?
    ORDER BY bookings.start_time
    """, (selected_date,))

    return cursor.fetchall()


def room_has_booking(
    room_id,
    selected_date
):

    cursor.execute("""
    SELECT booking_id
    FROM bookings
    WHERE room_id = ?
    AND booking_date = ?
    """, (
        room_id,
        selected_date
    ))

    return cursor.fetchone() is not None


# ============================================================
# SIDEBAR
# ============================================================

with st.sidebar:

    st.markdown("## 🏢 Meeting Manager")

    st.divider()

    st.markdown("### Navigation")

    page = st.radio(
        "Navigation",
        [
            "🏠 Dashboard",
            "📅 Book a Room",
            "📋 Bookings",
            "🏢 Room Information"
        ],
        label_visibility="collapsed"
    )

    st.divider()

    st.markdown("### Smart Allocation")

    st.write(
        "Automatically assigns the most suitable "
        "available room based on capacity, "
        "facilities and schedule."
    )

# ============================================================
# MAIN TITLE
# ============================================================

st.markdown(
    '<div class="main-title">'
    '🏢 SMART MEETING ROOM ALLOCATION'
    '</div>',
    unsafe_allow_html=True
)

st.markdown(
    '<div class="subtitle">'
    'Intelligent room booking and resource management system'
    '</div>',
    unsafe_allow_html=True
)

# ============================================================
# DASHBOARD
# ============================================================

if page == "🏠 Dashboard":

    st.markdown(
        '<div class="section-heading">'
        '📊 Dashboard'
        '</div>',
        unsafe_allow_html=True
    )

    rooms = get_rooms()

    today = date.today().strftime("%Y-%m-%d")

    # Count rooms having at least one booking today
    booked_room_ids = set()

    for room in rooms:

        if room_has_booking(
            room[0],
            today
        ):
            booked_room_ids.add(room[0])

    total_rooms = len(rooms)

    booked_rooms = len(booked_room_ids)

    available_rooms = (
        total_rooms - booked_rooms
    )

    total_capacity = sum(
        room[2]
        for room in rooms
    )

    # ========================================================
    # METRICS
    # ========================================================

    col1, col2, col3, col4 = st.columns(4)

    with col1:

        st.metric(
            "🏢 Total Rooms",
            total_rooms
        )

    with col2:

        st.metric(
            "🟢 Available Rooms",
            available_rooms
        )

    with col3:

        st.metric(
            "🔴 Booked Rooms",
            booked_rooms
        )

    with col4:

        st.metric(
            "👥 Total Capacity",
            total_capacity
        )

    # ========================================================
    # ROOM DISPLAY
    # ========================================================

    st.markdown(
        '<div class="section-heading">'
        '🏢 Meeting Rooms'
        '</div>',
        unsafe_allow_html=True
    )

    room_columns = st.columns(2)

    for index, room in enumerate(rooms):

        room_id = room[0]
        room_name = room[1]
        capacity = room[2]
        facilities = room[3]

        occupied = room_has_booking(
            room_id,
            today
        )

        with room_columns[index % 2]:

            with st.container(border=True):

                st.subheader(
                    f"🏢 {room_name}"
                )

                st.write(
                    f"👥 **Capacity:** "
                    f"{capacity} participants"
                )

                st.write(
                    f"🛠️ **Facilities:** "
                    f"{facilities}"
                )

                if occupied:

                    st.error(
                        "🔴 BOOKED"
                    )

                else:

                    st.success(
                        "🟢 AVAILABLE"
                    )

# ============================================================
# BOOK A ROOM
# ============================================================

elif page == "📅 Book a Room":

    st.markdown(
        '<div class="section-heading">'
        '📅 Book a Meeting Room'
        '</div>',
        unsafe_allow_html=True
    )

    st.info(
        "The system automatically selects the "
        "smallest suitable room based on your "
        "requirements."
    )

    col1, col2 = st.columns(2)

    with col1:

        meeting_name = st.text_input(
            "Meeting Name",
            placeholder="Example: Project Discussion"
        )

        organizer = st.text_input(
            "Organizer",
            placeholder="Enter organizer name"
        )

        participants = st.number_input(
            "Number of Participants",
            min_value=1,
            max_value=100,
            value=4,
            step=1
        )

    with col2:

        booking_date = st.date_input(
            "Meeting Date",
            value=date.today()
        )

        start_time = st.time_input(
            "Start Time",
            value=time(9, 0)
        )

        end_time = st.time_input(
            "End Time",
            value=time(10, 0)
        )

    st.markdown("### 🛠️ Required Facilities")

    required_facilities = st.multiselect(
        "Select required facilities",
        [
            "Projector",
            "Whiteboard"
        ]
    )

    st.write("")

    if st.button(
        "🚀 Allocate Meeting Room",
        type="primary",
        use_container_width=True
    ):

        if not meeting_name.strip():

            st.error(
                "Please enter the meeting name."
            )

        elif not organizer.strip():

            st.error(
                "Please enter the organizer name."
            )

        elif end_time <= start_time:

            st.error(
                "End time must be after start time."
            )

        else:

            selected_date = (
                booking_date.strftime("%Y-%m-%d")
            )

            start_string = (
                start_time.strftime("%H:%M")
            )

            end_string = (
                end_time.strftime("%H:%M")
            )

            room = find_best_room(
                participants,
                required_facilities,
                selected_date,
                start_string,
                end_string
            )

            if room is None:

                st.error(
                    "❌ No suitable room is available "
                    "for the selected time, capacity "
                    "and facilities."
                )

            else:

                room_id = room[0]
                room_name = room[1]
                capacity = room[2]
                facilities = room[3]

                cursor.execute("""
                INSERT INTO bookings (
                    meeting_name,
                    organizer,
                    participants,
                    room_id,
                    booking_date,
                    start_time,
                    end_time
                )
                VALUES (?, ?, ?, ?, ?, ?, ?)
                """, (
                    meeting_name,
                    organizer,
                    participants,
                    room_id,
                    selected_date,
                    start_string,
                    end_string
                ))

                conn.commit()

                st.success(
                    "🎉 YOUR SLOT IS BOOKED!"
                )

                st.info(
                    f"""
                    **Meeting:** {meeting_name}

                    **Room:** {room_name}

                    **Participants:** {participants}

                    **Date:** {selected_date}

                    **Time:** {start_string} - {end_string}

                    **Facilities:** {facilities}
                    """
                )

                st.balloons()

# ============================================================
# BOOKINGS
# ============================================================

elif page == "📋 Bookings":

    st.markdown(
        '<div class="section-heading">'
        '📋 Meeting Schedule'
        '</div>',
        unsafe_allow_html=True
    )

    selected_date = st.date_input(
        "Select Date",
        value=date.today(),
        key="booking_view_date"
    )

    selected_date_string = (
        selected_date.strftime("%Y-%m-%d")
    )

    bookings = get_bookings(
        selected_date_string
    )

    if not bookings:

        st.info(
            "📭 No meetings are scheduled "
            "for this date."
        )

    else:

        st.write(
            f"### {len(bookings)} scheduled meeting(s)"
        )

        for booking in bookings:

            booking_id = booking[0]
            meeting_name = booking[1]
            organizer = booking[2]
            participants = booking[3]
            room_name = booking[4]
            start = booking[5]
            end = booking[6]

            with st.container(border=True):

                col1, col2, col3, col4 = st.columns(
                    [3, 2, 2, 1]
                )

                with col1:

                    st.subheader(
                        f"📌 {meeting_name}"
                    )

                    st.write(
                        f"Organizer: **{organizer}**"
                    )

                with col2:

                    st.write(
                        f"🏢 **{room_name}**"
                    )

                    st.write(
                        f"👥 {participants} participants"
                    )

                with col3:

                    st.write(
                        f"📅 {selected_date_string}"
                    )

                    st.write(
                        f"⏰ {start} - {end}"
                    )

                with col4:

                    if st.button(
                        "Cancel",
                        key=f"cancel_{booking_id}"
                    ):

                        cursor.execute("""
                        DELETE FROM bookings
                        WHERE booking_id = ?
                        """, (booking_id,))

                        conn.commit()

                        st.success(
                            "Booking cancelled."
                        )

                        st.rerun()

# ============================================================
# ROOM INFORMATION
# ============================================================

elif page == "🏢 Room Information":

    st.markdown(
        '<div class="section-heading">'
        '🏢 Room Information'
        '</div>',
        unsafe_allow_html=True
    )

    st.info(
        "View the capacity and facilities "
        "available in each meeting room."
    )

    rooms = get_rooms()

    room_columns = st.columns(2)

    for index, room in enumerate(rooms):

        room_id = room[0]
        room_name = room[1]
        capacity = room[2]
        facilities = room[3]

        with room_columns[index % 2]:

            with st.container(border=True):

                st.subheader(
                    f"🏢 {room_name}"
                )

                st.write(
                    f"👥 **Capacity:** "
                    f"{capacity} participants"
                )

                st.write(
                    f"🛠️ **Facilities:** "
                    f"{facilities}"
                )

                st.divider()

                if room_has_booking(
                    room_id,
                    date.today().strftime("%Y-%m-%d")
                ):

                    st.error(
                        "🔴 Booked today"
                    )

                else:

                    st.success(
                        "🟢 Available today"
                    )

# ============================================================
# FOOTER
# ============================================================

st.divider()

st.caption(
    "Smart Meeting Room Allocation System "
    "• Python • Streamlit • SQLite"
)